on:
    push:
        branches: main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Install Dependencies
              run: composer install

            - name: Migrate DB
              run: |
                php artisan migrate --force
              env:
                APP_ENV: production
                DB_CONNECTION: mysql
                DB_HOST: ${{ secrets.ap-southeast-2.sql.xata.sh}}
                DB_PORT: 3306
                DB_DATABASE: ${{ secrets.laravel-vercel:main}}
                DB_USERNAME: ${{ secrets.https://app.xata.io/workspaces/Lois-Jerson-A-Gonzales }}
                DB_PASSWORD: ${{ secrets.xau_Ee2chgH3TLR5JexGcEP7iyLfu9wJUW6P1 }}
                MYSQL_ATTR_SSL_CA: /etc/ssl/certs/ca-certificates.crt

            - name: Deploy to Vercel
              run: vercel deploy --prod --token=${{ secrets.zH0cfFZF2EPW8OJpJAgF0wUs }}
              env:
                VERCEL_ORG_ID: ${{ secrets.OqQEyKh5Evf0A8IEMkVwdu96 }}
                VERCEL_PROJECT_ID: ${{ secrets.prj_Aud7PIB70p0lpAkNXzlSDnye7jjX }}
